version: '{branch}-{build}'

configuration:
  - Debug
  - Debug_Lite
  - Release_Lite
  - Release

skip_commits:
  files:
    - docs/*

skip_tags: true

build:
  project: MLAPI.sln
  verbosity: minimal

after_build:
  - cd C:\projects\mlapi-a6wbv
  - powershell "& "".\BuildUnityPackages.ps1"""

artifacts:
  - path: '*.unitypackage'

image: Visual Studio 2017

before_build:
  - nuget restore

matrix:
  fast_finish: true

for:
-
  matrix:
    only:
      - configuration: Debug
  artifacts:
  - path: 'MLAPI\bin\Debug\*\*MLAPI*'
  before_package:
  - cp MLAPI/bin/Debug/net35/MLAPI.* MLAPI/bin
  test:
    assemblies:
      - 'MLAPI-Tests\bin\Debug\*\MLAPI-Tests.dll'
-
  matrix:
    only:
      - configuration: Debug_Lite
  artifacts:
  - path: 'MLAPI\bin\Lite\Debug\*\*MLAPI*'
  before_package:
  - cp MLAPI/bin/Lite/Debug/net35/MLAPI.* MLAPI/bin
  test:
    assemblies:
      - 'MLAPI-Tests\bin\Lite\Debug\*\MLAPI-Tests.dll'
-
  matrix:
    only:
      - configuration: Release
  artifacts:
  - path: 'MLAPI\bin\Release\*\*MLAPI*'
  before_package:
  - cp MLAPI/bin/Release/net35/MLAPI.* MLAPI/bin
  test:
    assemblies:
      - 'MLAPI-Tests\bin\Release\*\MLAPI-Tests.dll'
  cache:
  - '%APPDATA%\npm'
  install:
  - npm install -g semantic-release
  deploy_script:
  - semantic-release
-
  matrix:
    only:
      - configuration: Release_Lite
  artifacts:
  - path: 'MLAPI\bin\Lite\Release\*\*MLAPI*'
  before_package:
  - cp MLAPI/bin/Lite/Release/net35/MLAPI.* MLAPI/bin
  test:
    assemblies:
      - 'MLAPI-Tests\bin\Lite\Release\*\MLAPI-Tests.dll'

# Deploy API reference
deploy_script:
  - cd C:\projects\mlapi-a6wbv
  - cp Libraries/Unity/* ./MLAPI/bin/Debug/*/
  - Libraries\Internal\ApiParser\ApiParser.exe ./MLAPI/bin/Debug/net35/MLAPI.dll ./MLAPI/bin/Debug/net35/MLAPI.xml ./docs/_data/api.yml ./docs/_api/
  - git add docs
  - git commit -m "docs(api): Updated API docs (Automated)"
  - git push